const ActionType = {
    LAYOUT_BLOCK: 'LAYOUT_BLOCK',
    LAYOUT_UNBLOCK: 'LAYOUT_UNBLOCK',
    //Auth
    UPDATE_USERDATA: 'UPDATE_USERDATA',
    RESET_USERDATA: 'RESET_USERDATA'

}

export default ActionType